"""empty message

Revision ID: 01a4d437be62
Revises: e6accfbb59f8
Create Date: 2019-12-13 17:40:35.281877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a4d437be62'
down_revision = 'e6accfbb59f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('attendees', sa.Text(), nullable=True))
    op.add_column('google_calendar_events', sa.Column('conference_data', sa.Text(), nullable=True))
    op.add_column('google_calendar_events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('google_calendar_events', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('google_calendar_events', sa.Column('google_id', sa.String(length=200), nullable=False))
    op.add_column('google_calendar_events', sa.Column('ical_uid', sa.String(length=200), nullable=False))
    op.add_column('google_calendar_events', sa.Column('organizer_email', sa.String(length=200), nullable=False))
    op.add_column('google_calendar_events', sa.Column('organizer_self', sa.Boolean(), nullable=False))
    op.add_column('google_calendar_events', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('google_calendar_events', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('google_calendar_events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'google_calendar_events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_calendar_events', type_='foreignkey')
    op.drop_column('google_calendar_events', 'user_id')
    op.drop_column('google_calendar_events', 'summary')
    op.drop_column('google_calendar_events', 'start_time')
    op.drop_column('google_calendar_events', 'organizer_self')
    op.drop_column('google_calendar_events', 'organizer_email')
    op.drop_column('google_calendar_events', 'ical_uid')
    op.drop_column('google_calendar_events', 'google_id')
    op.drop_column('google_calendar_events', 'end_time')
    op.drop_column('google_calendar_events', 'description')
    op.drop_column('google_calendar_events', 'conference_data')
    op.drop_column('google_calendar_events', 'attendees')
    # ### end Alembic commands ###
