"""empty message

Revision ID: 064cb5474b56
Revises: a868f1749096
Create Date: 2020-02-18 14:19:31.266073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064cb5474b56'
down_revision = 'a868f1749096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_api_repo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('github_api_owner_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_repos')
    # ### end Alembic commands ###
