"""empty message

Revision ID: 13d7490d3434
Revises: 7325284b2d33
Create Date: 2019-10-20 17:22:53.657150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d7490d3434'
down_revision = '7325284b2d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('sub_content', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sub_content')
    # ### end Alembic commands ###
