"""empty message

Revision ID: 18a4c66cb849
Revises: 85767ea1a394
Create Date: 2020-02-18 14:21:44.041498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a4c66cb849'
down_revision = '85767ea1a394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('github_api_issue_id', sa.Integer(), nullable=False),
    sa.Column('github_api_creator_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('github_api_opened_at', sa.DateTime(), nullable=False),
    sa.Column('github_api_closed_at', sa.DateTime(), nullable=True),
    sa.Column('open_impact_score', sa.Float(), nullable=True),
    sa.Column('closure_impact_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_issues')
    # ### end Alembic commands ###
