"""empty message

Revision ID: 206841683ce2
Revises: 5ac377dc9171
Create Date: 2019-10-21 01:12:50.183815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206841683ce2'
down_revision = '5ac377dc9171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('raw_slack_events', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated')
    op.drop_column('raw_slack_events', 'last_updated')
    op.drop_column('posts', 'last_updated')
    # ### end Alembic commands ###
