"""empty message

Revision ID: 26beddeac06f
Revises: 01a4d437be62
Create Date: 2019-12-13 18:13:59.754516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26beddeac06f'
down_revision = '01a4d437be62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('google_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'google_calendar_events', 'google_calendar_users', ['google_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_calendar_events', type_='foreignkey')
    op.drop_column('google_calendar_events', 'google_user_id')
    # ### end Alembic commands ###
