"""empty message

Revision ID: 2bffd469813c
Revises: b33a569c0215
Create Date: 2019-12-12 20:27:55.047405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bffd469813c'
down_revision = 'b33a569c0215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('google_calendar_users', 'refresh_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_users', 'refresh_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_table('google_calendar_events')
    # ### end Alembic commands ###
