"""empty message

Revision ID: 3a208a3a29d8
Revises: 454bb29c4809
Create Date: 2019-10-28 22:10:30.668570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a208a3a29d8'
down_revision = '454bb29c4809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('slack_timezone_label', sa.String(length=100), nullable=True))
    op.add_column('slack_users', sa.Column('slack_timezone_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_users', 'slack_timezone_offset')
    op.drop_column('slack_users', 'slack_timezone_label')
    # ### end Alembic commands ###
