"""empty message

Revision ID: 454bb29c4809
Revises: 023c51e190e7
Create Date: 2019-10-28 16:43:26.762750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '454bb29c4809'
down_revision = '023c51e190e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_api_id', sa.String(length=100), nullable=False),
    sa.Column('slack_team_id', sa.Integer(), nullable=False),
    sa.Column('slack_email_address', sa.String(length=300), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('slack_username', sa.String(length=100), nullable=False),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.Column('is_deleted_on_slack', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slack_team_id'], ['slack_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('slack_teams', sa.Column('authenticated_at', sa.DateTime(), nullable=True))
    # op.create_unique_constraint(None, 'slack_teams', ['slack_team_api_id'])
    op.alter_column('slack_teams', 'slack_team_id', new_column_name='slack_team_api_id')
    op.drop_column('slack_teams', 'datetime_authenticated')
    op.drop_column('slack_teams', 'install_slack_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_teams', sa.Column('install_slack_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('slack_teams', sa.Column('datetime_authenticated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'slack_teams', type_='unique')
    op.alter_column('slack_teams', 'slack_team_api_id', new_column_name='slack_team_id')
    op.drop_column('slack_teams', 'authenticated_at')
    op.drop_table('slack_users')
    # ### end Alembic commands ###
