"""empty message

Revision ID: 47ca4efc541f
Revises: e8be42e6bcb5
Create Date: 2020-02-03 00:44:35.342934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ca4efc541f'
down_revision = 'e8be42e6bcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus_length', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('focus_preference', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('workday_end', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('workday_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workday_start')
    op.drop_column('users', 'workday_end')
    op.drop_column('users', 'focus_preference')
    op.drop_column('users', 'focus_length')
    # ### end Alembic commands ###
