"""empty message

Revision ID: 5ac377dc9171
Revises: 13d7490d3434
Create Date: 2019-10-21 00:48:20.766699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac377dc9171'
down_revision = '13d7490d3434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_slack_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.JSON(none_as_null=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_slack_events')
    # ### end Alembic commands ###
