"""empty message

Revision ID: 5f2726a00f9b
Revises: 023c51e190e7
Create Date: 2019-10-26 16:43:17.410560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2726a00f9b'
down_revision = '023c51e190e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sub_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('sub_content', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
