"""empty message

Revision ID: 633689a9a38e
Revises: 064cb5474b56
Create Date: 2020-02-18 14:20:39.232697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633689a9a38e'
down_revision = '064cb5474b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('github_api_repo_id', sa.Integer(), nullable=False),
    sa.Column('github_api_author_id', sa.Integer(), nullable=False),
    sa.Column('github_api_committer_id', sa.Integer(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('github_api_committed_at', sa.DateTime(), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('edit_points', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_commits')
    # ### end Alembic commands ###
