"""empty message

Revision ID: 7a29759678c8
Revises: 47ca4efc541f
Create Date: 2020-02-19 20:29:30.461319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a29759678c8'
down_revision = '47ca4efc541f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'focus_preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus_preference', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
