"""empty message

Revision ID: 80aeb500b4fa
Revises: bd00f5700734
Create Date: 2020-02-20 00:28:51.412888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aeb500b4fa'
down_revision = 'bd00f5700734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus_length', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('workday_end', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('workday_start', sa.DateTime(), nullable=True))
    op.drop_column('users', 'focus_preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus_preference', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('users', 'workday_start')
    op.drop_column('users', 'workday_end')
    op.drop_column('users', 'focus_length')
    # ### end Alembic commands ###
