"""empty message

Revision ID: 85945c7ca481
Revises: 80aeb500b4fa
Create Date: 2020-02-20 15:19:56.511549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85945c7ca481'
down_revision = '80aeb500b4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_report_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_utc', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slack_conversation_read_count', sa.Integer(), nullable=True),
    sa.Column('slack_user_event_count', sa.Integer(), nullable=True),
    sa.Column('google_calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('google_calendar_event_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['google_calendar_event_id'], ['google_calendar_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_report_rows')
    # ### end Alembic commands ###
