"""empty message

Revision ID: 8c8cc142f350
Revises: cd0b685103a7
Create Date: 2019-11-22 22:52:05.686118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8cc142f350'
down_revision = 'cd0b685103a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_run_time', sa.Float(), nullable=True),
    sa.Column('job_state', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###
