"""empty message

Revision ID: 9034859ebb8a
Revises: 26beddeac06f
Create Date: 2019-12-13 18:51:03.848211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9034859ebb8a'
down_revision = '26beddeac06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('google_calendar_events', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('google_calendar_events', 'organizer_self',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_calendar_events', 'organizer_self',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('google_calendar_events', 'updated_at')
    op.drop_column('google_calendar_events', 'created_at')
    # ### end Alembic commands ###
