"""empty message

Revision ID: 968080e1c896
Revises: 20b03104caee
Create Date: 2020-03-07 02:22:08.190477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968080e1c896'
down_revision = 'f2d064800e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_report_rows_google_calendar_event_id_fkey', 'activity_report_rows', type_='foreignkey')
    op.create_foreign_key('activity_report_rows_google_calendar_event_id_fkey', 'activity_report_rows', 'google_calendar_events', ['google_calendar_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_report_rows_google_calendar_event_id_fkey', 'activity_report_rows', type_='foreignkey')
    op.create_foreign_key('activity_report_rows_google_calendar_event_id_fkey', 'activity_report_rows', 'google_calendar_events', ['google_calendar_event_id'], ['id'])
    # ### end Alembic commands ###
