"""empty message

Revision ID: a04ccf39e33f
Revises: b28d97611d74
Create Date: 2019-11-28 16:20:06.535891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04ccf39e33f'
down_revision = 'b28d97611d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_conversation_api_id', sa.String(length=100), nullable=False),
    sa.Column('slack_team_id', sa.Integer(), nullable=False),
    sa.Column('conversation_type', sa.String(length=100), nullable=False),
    sa.Column('conversation_name', sa.String(length=100)),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slack_team_id'], ['slack_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_conversations')
    # ### end Alembic commands ###
