"""empty message

Revision ID: a0d43a8dc6a5
Revises: a04ccf39e33f
Create Date: 2019-11-28 23:51:44.170033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d43a8dc6a5'
down_revision = 'a04ccf39e33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_conversation_query_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_start_time', sa.DateTime(), nullable=False),
    sa.Column('query_end_time', sa.DateTime(), nullable=True),
    sa.Column('slack_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slack_user_id'], ['slack_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack_conversation_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.Integer(), nullable=False),
    sa.Column('slack_conversation_id', sa.Integer(), nullable=False),
    sa.Column('query_datetime', sa.DateTime(), nullable=False),
    sa.Column('last_read_datetime', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('slack_conversation_query_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slack_conversation_id'], ['slack_conversations.id'], ),
    sa.ForeignKeyConstraint(['slack_conversation_query_run_id'], ['slack_conversation_query_runs.id'], ),
    sa.ForeignKeyConstraint(['slack_user_id'], ['slack_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_conversation_queries')
    op.drop_table('slack_conversation_query_runs')
    # ### end Alembic commands ###
