"""empty message

Revision ID: a868f1749096
Revises: 1595547e524d
Create Date: 2020-02-06 13:29:18.109730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a868f1749096'
down_revision = '1595547e524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_users', sa.Column('github_api_user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_users', 'github_api_user_id')
    # ### end Alembic commands ###
