"""empty message

Revision ID: acedd8d0829b
Revises: bf1866667f1d
Create Date: 2020-03-07 19:14:30.349623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acedd8d0829b'
down_revision = 'bf1866667f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('github_api_comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('github_api_author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('github_api_parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('github_api_written_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('github_api_edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('impact_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comment_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
