"""empty message

Revision ID: b33a569c0215
Revises: d4a51d5d8b6f
Create Date: 2019-11-30 14:46:21.298010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a569c0215'
down_revision = 'd4a51d5d8b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('google_calendar_users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_calendar_users', 'updated_at')
    op.drop_column('google_calendar_users', 'created_at')
    # ### end Alembic commands ###
