"""empty message

Revision ID: b780e0351426
Revises: e8be42e6bcb5
Create Date: 2020-01-20 12:23:06.089365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b780e0351426'
down_revision = 'e8be42e6bcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_run_time', sa.Float(), nullable=True),
    sa.Column('job_state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('github_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_user_api_id', sa.String(length=100), nullable=True),
    sa.Column('github_email_address', sa.String(length=300), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=False),
    sa.Column('github_oauth_access_token', sa.String(length=200), nullable=True),
    sa.Column('is_deleted_on_github', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_contr_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['github_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('contr_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['github_users.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['github_contr_repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_actions')
    op.drop_table('github_contr_repos')
    op.drop_table('github_users')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###
