"""empty message

Revision ID: b971e4ef181b
Revises: 968080e1c896
Create Date: 2020-03-07 18:17:12.258140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b971e4ef181b'
down_revision = '968080e1c896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_report_rows', sa.Column('focused_work_period_start_utc', sa.DateTime(), nullable=True))
    op.add_column('activity_report_rows', sa.Column('is_collaborative_time', sa.Boolean(), nullable=True))
    op.add_column('activity_report_rows', sa.Column('is_focus_time', sa.Boolean(), nullable=True))
    op.add_column('activity_report_rows', sa.Column('is_refocus_time', sa.Boolean(), nullable=True))
    op.add_column('activity_report_rows', sa.Column('is_workday_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_report_rows', 'is_workday_time')
    op.drop_column('activity_report_rows', 'is_refocus_time')
    op.drop_column('activity_report_rows', 'is_focus_time')
    op.drop_column('activity_report_rows', 'is_collaborative_time')
    op.drop_column('activity_report_rows', 'focused_work_period_start_utc')
    # ### end Alembic commands ###
