"""empty message

Revision ID: bd360eab6c52
Revises: a0d43a8dc6a5
Create Date: 2019-11-29 14:44:46.502468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd360eab6c52'
down_revision = 'a0d43a8dc6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_conversation_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_conversation_query_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.Integer(), nullable=False),
    sa.Column('slack_conversation_id', sa.Integer(), nullable=False),
    sa.Column('period_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('period_end_datetime', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slack_conversation_id'], ['slack_conversations.id'], ),
    sa.ForeignKeyConstraint(['slack_conversation_query_id'], ['slack_conversation_queries.id'], ),
    sa.ForeignKeyConstraint(['slack_user_id'], ['slack_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_conversation_query_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_conversation_reads')
    # ### end Alembic commands ###
