"""empty message

Revision ID: bf1866667f1d
Revises: 20b03104caee
Create Date: 2020-03-01 21:53:39.959215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1866667f1d'
down_revision = '20b03104caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_issues', sa.Column('github_api_closer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_issues', 'github_api_closer_id')
    # ### end Alembic commands ###
