"""empty message

Revision ID: cc1e8044258e
Revises: 5a1a834f16e0
Create Date: 2019-12-15 00:30:48.483234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1e8044258e'
down_revision = '5a1a834f16e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=False),
    sa.Column('ical_uid', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer_email', sa.String(length=200), nullable=False),
    sa.Column('organizer_self', sa.Boolean(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('conference_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('google_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['google_user_id'], ['google_calendar_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('google_calendar_users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('google_calendar_users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('google_calendar_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('google_calendar_users', 'refresh_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.create_foreign_key(None, 'google_calendar_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_calendar_users', type_='foreignkey')
    op.alter_column('google_calendar_users', 'refresh_token',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('google_calendar_users', 'user_id')
    op.drop_column('google_calendar_users', 'updated_at')
    op.drop_column('google_calendar_users', 'created_at')
    op.drop_table('google_calendar_events')
    # ### end Alembic commands ###
