"""empty message

Revision ID: cd0b685103a7
Revises: 3a208a3a29d8
Create Date: 2019-10-30 13:42:03.095843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0b685103a7'
down_revision = '3a208a3a29d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('authentication_oauth_access_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_users', 'authentication_oauth_access_token')
    # ### end Alembic commands ###
