"""empty message

Revision ID: d4a51d5d8b6f
Revises: bd360eab6c52
Create Date: 2019-11-29 18:12:07.598491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a51d5d8b6f'
down_revision = 'bd360eab6c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_email', sa.String(length=300), nullable=False),
    sa.Column('auth_token', sa.String(length=300), nullable=False),
    sa.Column('refresh_token', sa.String(length=300), nullable=False),
    sa.Column('scopes', sa.String(length=300), nullable=False),
    sa.Column('primary_timeZone', sa.String(length=300), nullable=False),
    sa.Column('primary_etag', sa.String(length=300), nullable=False),
    sa.Column('primary_color_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_calendar_users')
    # ### end Alembic commands ###
