"""empty message

Revision ID: e37e966bac29
Revises: e3995cedd8e6
Create Date: 2020-02-17 14:59:40.289474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37e966bac29'
down_revision = 'e3995cedd8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_api_comment_id', sa.Integer(), nullable=False),
    sa.Column('github_api_author_id', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.String(length=30), nullable=False),
    sa.Column('github_api_parent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'comment_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_comments')

    # ### end Alembic commands ###
