"""empty message

Revision ID: e6accfbb59f8
Revises: 2bffd469813c
Create Date: 2019-12-13 16:13:26.648425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6accfbb59f8'
down_revision = '2bffd469813c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'google_calendar_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'google_calendar_users', type_='foreignkey')
    op.drop_column('google_calendar_users', 'user_id')
    # ### end Alembic commands ###
