"""empty message

Revision ID: e8be42e6bcb5
Revises: 588f17ec0cd4
Create Date: 2020-01-08 14:43:03.616345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8be42e6bcb5'
down_revision = '588f17ec0cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slack_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slack_users_user_id_fkey', 'slack_users', type_='foreignkey')
    op.drop_column('slack_users', 'user_id')
    # ### end Alembic commands ###
