"""empty message

Revision ID: fac7e073b9b5
Revises: cc1e8044258e
Create Date: 2019-12-15 22:46:34.021348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac7e073b9b5'
down_revision = 'cc1e8044258e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('google_calendar_user_id', sa.Integer(), nullable=True))
    op.add_column('google_calendar_events', sa.Column('json_data', sa.JSON(none_as_null=True), nullable=False))
    op.drop_constraint('google_calendar_events_google_user_id_fkey', 'google_calendar_events', type_='foreignkey')
    op.drop_constraint('google_calendar_events_user_id_fkey', 'google_calendar_events', type_='foreignkey')
    op.create_foreign_key(None, 'google_calendar_events', 'google_calendar_users', ['google_calendar_user_id'], ['id'])
    op.drop_column('google_calendar_events', 'google_user_id')
    op.drop_column('google_calendar_events', 'attendees')
    op.drop_column('google_calendar_events', 'conference_data')
    op.drop_column('google_calendar_events', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_calendar_events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('google_calendar_events', sa.Column('conference_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_calendar_events', sa.Column('attendees', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('google_calendar_events', sa.Column('google_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'google_calendar_events', type_='foreignkey')
    op.create_foreign_key('google_calendar_events_user_id_fkey', 'google_calendar_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key('google_calendar_events_google_user_id_fkey', 'google_calendar_events', 'google_calendar_users', ['google_user_id'], ['id'])
    op.drop_column('google_calendar_events', 'json_data')
    op.drop_column('google_calendar_events', 'google_calendar_user_id')
    # ### end Alembic commands ###
