"""empty message

Revision ID: fc5776f9f574
Revises: 454bb29c4809
Create Date: 2019-10-28 18:06:28.288455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5776f9f574'
down_revision = '454bb29c4809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_users', sa.Column('slack_timestamp_label', sa.String(length=100), nullable=True))
    op.add_column('slack_users', sa.Column('slack_timestamp_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_users', 'slack_timestamp_offset')
    op.drop_column('slack_users', 'slack_timestamp_label')
    # ### end Alembic commands ###
